# -*- coding: utf-8 -*-
"""Celsius_a_Fahrenheit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XodZWUQt-F-AhQup2eP-3dcHYKVTSqWB
"""

import tensorflow as tf
import numpy as np

# Datos de entrada
celsius = np.array([-40, -10, 0, 8, 15, 22, 38], dtype=float)
fahrenheit = np.array([-40, 14, 32, 46, 59, 72, 100])

# Definir el modelo correctamente
modelo = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,)),  # Definir la capa de entrada explícitamente
    tf.keras.layers.Dense(units=1)      # Capa densa con una neurona
])
print("Modelo creado exitosamente")

modelo.compile(
  optimizer=tf.keras.optimizers.Adam(0.1),
  loss="mean_squared_error"
)

print("Comenzaremos este entrenamiento")
historial = modelo.fit(celsius, fahrenheit, epochs=1000, verbose=False)
print("Modelo entrenado !!!")

import matplotlib.pyplot as plt
plt.xlabel("# Epoca")
plt.ylabel("Magnitud de pérdida")
plt.plot(historial.history["loss"])

print("Hagamos una predicción")

# Convertir el valor a un array de NumPy con la forma correcta
entrada = np.array([100.0], dtype=float)

# Hacer la predicción
resultado = modelo.predict(entrada)

# Mostrar el resultado de forma clara
print(f"El resultado es {resultado[0][0]:.2f} Fahrenheit !!!")

print("Variables internas del modelo")
print(modelo.get_weights())